'use client';
import {useEffect,useMemo,useState} from 'react';
import {readings,prompts} from '../lib/content';
import {supabase} from '../lib/supabase';

type Eval={total:number;scores:Record<string,number>;strengths:string[];priorities:string[];grammar_examples:{original:string;issue:string;hint:string}[];revision_goal:string;coach_message:string;next_level:string};
const rubric=['Ideas & Content','Argument & Reasoning','Evidence & Examples','Organization','Introduction & Conclusion','Vocabulary','Sentence Structure','Grammar & Mechanics'];
export default function Home(){
 const [tab,setTab]=useState('home'); const [reading,setReading]=useState(readings[0]); const [prompt,setPrompt]=useState(prompts[0]); const [answer,setAnswer]=useState(''); const [self,setSelf]=useState(''); const [ev,setEv]=useState<Eval|null>(null); const [busy,setBusy]=useState(false); const [role,setRole]=useState<'student'|'parent'>('student'); const [history,setHistory]=useState<any[]>([]);
 useEffect(()=>{const h=JSON.parse(localStorage.getItem('cec-history')||'[]');setHistory(h)},[]);
 const save=(x:any)=>{const h=[x,...history].slice(0,50);setHistory(h);localStorage.setItem('cec-history',JSON.stringify(h))};
 async function evaluate(mode:string){setBusy(true);setEv(null);try{const r=await fetch('/api/evaluate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,prompt:prompt.title+' — '+prompt.instruction,passage:mode==='reading'?reading.body:'',response:answer,revision:false})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Evaluation failed');setEv(j);save({date:new Date().toISOString(),activity:mode==='reading'?reading.title:prompt.title,total:j.total,scores:j.scores});}catch(e:any){alert(e.message)}finally{setBusy(false)}}
 const stats=useMemo(()=>{if(!history.length)return {avg:0,count:0};return {avg:Math.round(history.reduce((a,b)=>a+(b.total||0),0)/history.length),count:history.length}},[history]);
 return <main className="min-h-screen"><header className="sticky top-0 z-10 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><div><div className="text-xl font-black tracking-tight">Chaarvee <span className="text-indigo-600">English Coach</span></div><div className="text-xs text-slate-500">Grade 8 → Grade 9 academic writing</div></div><div className="flex gap-2">{(['student','parent'] as const).map(r=><button key={r} onClick={()=>setRole(r)} className={`rounded-full px-4 py-2 text-sm font-semibold ${role===r?'bg-indigo-600 text-white':'bg-slate-100 text-slate-700'}`}>{r==='student'?'Student':'Parent'}</button>)}</div></div></header>
 <div className="mx-auto grid max-w-6xl grid-cols-12 gap-5 p-5"><aside className="card col-span-12 p-3 md:col-span-3"><nav className="grid gap-2">{[['home','🏠 Dashboard'],['reading','📚 Reading Lab'],['writing','✍️ Writing Coach'],['progress','📈 Progress']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-4 py-3 text-left text-sm font-semibold ${tab===id?'bg-indigo-50 text-indigo-700':'hover:bg-slate-50'}`}>{label}</button>)}</nav><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-xs text-slate-600"><b>Coach rule:</b> I will help you improve your writing, but I will not write the answer for you.</div></aside>
 <section className="col-span-12 md:col-span-9">{tab==='home'&&<><div className="grid gap-4 md:grid-cols-3"><div className="card p-5"><div className="text-sm text-slate-500">Practice sessions</div><div className="mt-2 text-3xl font-black">{stats.count}</div></div><div className="card p-5"><div className="text-sm text-slate-500">Average score</div><div className="mt-2 text-3xl font-black">{stats.avg||'—'}<span className="text-base text-slate-400">/40</span></div></div><div className="card p-5"><div className="text-sm text-slate-500">Current focus</div><div className="mt-2 font-bold">Evidence → reasoning</div></div></div><div className="card mt-5 p-7"><div className="text-xs font-bold uppercase tracking-widest text-indigo-600">Today’s recommended path</div><h1 className="mt-2 text-3xl font-black">Read → Think → Write → Revise</h1><p className="mt-3 max-w-2xl text-slate-600">Choose an age-appropriate passage, answer the comprehension questions, then write a short response. The coach will identify your three highest-priority improvements.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>setTab('reading')} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">Start reading</button><button onClick={()=>setTab('writing')} className="rounded-xl border px-5 py-3 font-bold">Start writing</button></div></div></>}
 {tab==='reading'&&<div><div className="mb-4"><h2 className="text-2xl font-black">Reading Lab</h2><p className="text-slate-500">All starter texts are written for Grade 8–9 learners and avoid mature themes.</p></div><div className="grid gap-3 md:grid-cols-2">{readings.map(r=><button onClick={()=>{setReading(r);setTab('reading-detail')}} key={r.id} className="card p-5 text-left hover:border-indigo-300"><div className="text-xs font-bold text-indigo-600">{r.level} · {r.minutes} min</div><div className="mt-1 text-lg font-black">{r.title}</div><div className="mt-1 text-sm text-slate-500">{r.topic}</div></button>)}</div></div>}
 {tab==='reading-detail'&&<Activity reading={reading} answer={answer} setAnswer={setAnswer} self={self} setSelf={setSelf} ev={ev} busy={busy} evaluate={evaluate} back={()=>setTab('reading')}/>} 
 {tab==='writing'&&<div><h2 className="text-2xl font-black">Writing Coach</h2><p className="text-slate-500">Pick a prompt. Write independently. Then get coaching.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{prompts.map(p=><button key={p.id} onClick={()=>{setPrompt(p);setAnswer('');setEv(null);setTab('writing-detail')}} className="card p-5 text-left"><div className="text-xs font-bold text-indigo-600">{p.level} · {p.type}</div><div className="mt-1 text-lg font-black">{p.title}</div><div className="mt-2 text-sm text-slate-600">{p.words} words</div></button>)}</div></div>}
 {tab==='writing-detail'&&<Writing prompt={prompt} answer={answer} setAnswer={setAnswer} ev={ev} busy={busy} evaluate={()=>evaluate('writing')} back={()=>setTab('writing')}/>} 
 {tab==='progress'&&<Progress history={history}/>} </section></div></main>
}
function Activity({reading,answer,setAnswer,self,setSelf,ev,busy,evaluate,back}:{reading:any;answer:string;setAnswer:any;self:string;setSelf:any;ev:Eval|null;busy:boolean;evaluate:(m:string)=>void;back:()=>void}){return <div><button onClick={back} className="mb-4 text-sm font-bold text-indigo-600">← Back</button><article className="card p-7"><div className="text-xs font-bold uppercase tracking-widest text-indigo-600">{reading.level} · {reading.topic}</div><h2 className="mt-2 text-3xl font-black">{reading.title}</h2><div className="mt-6 whitespace-pre-line text-[17px] leading-8 text-slate-700">{reading.body}</div></article><div className="card mt-5 p-7"><h3 className="text-xl font-black">Think about it</h3><ol className="mt-4 list-decimal space-y-3 pl-6 text-slate-700">{reading.questions.map((q:string,i:number)=><li key={i}>{q}</li>)}</ol><textarea value={answer} onChange={e=>setAnswer(e.target.value)} className="mt-6 min-h-48 w-full rounded-xl border p-4 outline-none focus:ring-2 focus:ring-indigo-200" placeholder="Write your answers and a short evidence-based response here..."/><div className="mt-4 flex gap-3"><button disabled={busy||answer.length<30} onClick={()=>evaluate('reading')} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-40">{busy?'Coaching…':'Get feedback'}</button></div>{ev&&<Evaluation ev={ev}/>}</div></div>}
function Writing({prompt,answer,setAnswer,ev,busy,evaluate,back}:{prompt:any;answer:string;setAnswer:any;ev:Eval|null;busy:boolean;evaluate:()=>void;back:()=>void}){return <div><button onClick={back} className="mb-4 text-sm font-bold text-indigo-600">← Back</button><div className="card p-7"><div className="text-xs font-bold text-indigo-600">{prompt.level} · {prompt.type} · {prompt.words}</div><h2 className="mt-2 text-3xl font-black">{prompt.title}</h2><p className="mt-4 rounded-xl bg-indigo-50 p-4 text-slate-700">{prompt.instruction}</p><textarea value={answer} onChange={e=>setAnswer(e.target.value)} className="mt-5 min-h-96 w-full rounded-xl border p-5 text-[16px] leading-7 outline-none focus:ring-2 focus:ring-indigo-200" placeholder="Write your response here. The coach will evaluate your own work — it will not write the essay for you."/><div className="mt-3 flex items-center justify-between"><span className="text-sm text-slate-500">{answer.trim()?answer.trim().split(/\s+/).length:0} words</span><button disabled={busy||answer.trim().split(/\s+/).length<100} onClick={evaluate} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-40">{busy?'Evaluating…':'Submit for coaching'}</button></div>{ev&&<Evaluation ev={ev}/>}</div></div>}
function Evaluation({ev}:{ev:Eval}){return <div className="mt-7 border-t pt-7"><div className="flex items-end justify-between"><div><div className="text-sm font-bold text-slate-500">Coach evaluation</div><div className="text-4xl font-black">{ev.total}<span className="text-lg text-slate-400">/40</span></div></div><div className="rounded-full bg-indigo-50 px-4 py-2 text-sm font-bold text-indigo-700">{ev.next_level}</div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{rubric.map(k=><div key={k} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between text-sm"><span>{k}</span><b>{ev.scores?.[k]??0}/5</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-indigo-600" style={{width:`${((ev.scores?.[k]??0)/5)*100}%`}}/></div></div>)}</div><div className="mt-6 grid gap-5 md:grid-cols-2"><div><h4 className="font-black">What’s working</h4><ul className="mt-2 list-disc space-y-2 pl-5 text-sm text-slate-700">{ev.strengths?.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div><h4 className="font-black">Your 3 priorities</h4><ol className="mt-2 list-decimal space-y-2 pl-5 text-sm text-slate-700">{ev.priorities?.map((x,i)=><li key={i}>{x}</li>)}</ol></div></div><div className="mt-5 rounded-2xl bg-amber-50 p-5"><div className="font-black">Revision goal</div><p className="mt-1 text-sm text-slate-700">{ev.revision_goal}</p></div></div>}
function Progress({history}:{history:any[]}){return <div><h2 className="text-2xl font-black">Progress</h2><p className="text-slate-500">A simple record of practice. Cloud persistence can be enabled with Supabase.</p><div className="card mt-5 overflow-hidden"><div className="grid grid-cols-3 border-b bg-slate-50 p-4 text-xs font-bold uppercase text-slate-500"><span>Activity</span><span>Score</span><span>Date</span></div>{history.length?history.map((h,i)=><div key={i} className="grid grid-cols-3 border-b p-4 text-sm"><span className="font-semibold">{h.activity}</span><span>{h.total}/40</span><span>{new Date(h.date).toLocaleDateString()}</span></div>):<div className="p-8 text-center text-slate-500">No sessions yet. Start with Reading Lab.</div>}</div></div>}
