'use client';
import {useEffect,useMemo,useState} from 'react';
import {readings,prompts} from '../lib/content';
import {supabase} from '../lib/supabase';

type Eval={total:number;scores:Record<string,number>;strengths:string[];priorities:string[];grammar_examples:{original:string;issue:string;hint:string}[];revision_goal:string;coach_message:string;next_level:string};
type HistoryItem={date:string;activity:string;mode:string;total:number;scores:Record<string,number>;focus?:string};
const rubric=['Ideas & Content','Argument & Reasoning','Evidence & Examples','Organization','Introduction & Conclusion','Vocabulary','Sentence Structure','Grammar & Mechanics'];
const topics=['Random','Science','Technology','Environment','History','Geography','Arts & Music','Literature','Space','Animals & Nature','Sports','Inventions','Community','Culture','Ethics & Everyday Decisions'];
const levels=['Grade 8','Grade 8+','Grade 9','Grade 9+','AP/IB Foundation'];
const types=['Informational article','Short story','Historical narrative','Biography-style profile','Opinion piece','Science article','Literary passage','Compare/contrast texts'];
const writingTypes=['Opinion','Persuasive','Argumentative','Narrative','Descriptive','Expository','Compare & contrast','Literary analysis','Textual analysis','Research response','Creative writing'];

export default function Home(){
 const [tab,setTab]=useState('home'); const [role,setRole]=useState<'student'|'parent'>('student');
 const [reading,setReading]=useState<any>(readings[0]); const [prompt,setPrompt]=useState<any>(prompts[0]); const [answer,setAnswer]=useState(''); const [ev,setEv]=useState<Eval|null>(null); const [busy,setBusy]=useState(false); const [history,setHistory]=useState<HistoryItem[]>([]);
 const [rLevel,setRLevel]=useState('Grade 8+'); const [rTopic,setRTopic]=useState('Random'); const [rType,setRType]=useState(types[0]); const [rLength,setRLength]=useState('medium');
 const [wLevel,setWLevel]=useState('Grade 8+'); const [wTopic,setWTopic]=useState('Random'); const [wType,setWType]=useState('Argumentative');
 const [generated,setGenerated]=useState(false); const [focus,setFocus]=useState('balanced');
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem('cec-history')||'[]'))}catch{setHistory([])}},[]);
 useEffect(()=>{const f=weakestSkill(history);setFocus(f)},[history]);
 const stats=useMemo(()=>{if(!history.length)return {avg:0,count:0};return {avg:Math.round(history.reduce((a,b)=>a+(b.total||0),0)/history.length),count:history.length}},[history]);
 const save=(x:HistoryItem)=>{const h=[x,...history].slice(0,100);setHistory(h);localStorage.setItem('cec-history',JSON.stringify(h));};
 async function generateReading(){setBusy(true);try{const r=await fetch('/api/generate-reading',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({level:rLevel,topic:rTopic,type:rType,length:rLength,focus})});const j=await r.json();if(!r.ok)throw Error(j.error);setReading({...j,questions:Array.isArray(j.questions)?j.questions.map((q:any)=>typeof q==='string'?q:(q?.question||q?.prompt||q?.text||'')).filter(Boolean):[],writingChallenge:j.writingChallenge||j.writing_challenge||'',body:j.body||j.passage||j.article||'',id:'ai-'+Date.now(),level:rLevel,minutes:j.minutes||j.estimated_reading_minutes||8,topic:j.topic||rTopic});setAnswer('');setEv(null);setGenerated(true);setTab('reading-detail')}catch(e:any){alert(e.message)}finally{setBusy(false)}}
 async function generateWriting(){setBusy(true);try{const r=await fetch('/api/generate-writing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({level:wLevel,type:wType,topic:wTopic,focus,history})});const j=await r.json();if(!r.ok)throw Error(j.error);setPrompt({...j,id:'ai-'+Date.now(),words:`${j.words||400} words`});setAnswer('');setEv(null);setGenerated(true);setTab('writing-detail')}catch(e:any){alert(e.message)}finally{setBusy(false)}}
 async function evaluate(mode:string, revision=false, prior:any=null){setBusy(true);try{const p=mode==='reading'?(reading.title+' — '+(reading.questions||[]).join(' | ')):(prompt.title+' — '+prompt.instruction);const r=await fetch('/api/evaluate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,prompt:p,passage:mode==='reading'?reading.body:'',response:answer,revision,priorEvaluation:prior})});const j=await r.json();if(!r.ok)throw Error(j.error);setEv(j);save({date:new Date().toISOString(),activity:mode==='reading'?reading.title:prompt.title,mode,total:j.total,scores:j.scores,focus});}catch(e:any){alert(e.message)}finally{setBusy(false)}}
 return <main className="min-h-screen"><header className="sticky top-0 z-20 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><div className="text-xl font-black tracking-tight">Chaarvee <span className="text-indigo-600">English Coach</span></div><div className="text-xs text-slate-500">Adaptive Grade 8 → Grade 9 → AP/IB foundation</div></div><div className="flex gap-2">{(['student','parent'] as const).map(r=><button key={r} onClick={()=>setRole(r)} className={`rounded-full px-4 py-2 text-sm font-semibold ${role===r?'bg-indigo-600 text-white':'bg-slate-100 text-slate-700'}`}>{r==='student'?'Student':'Parent'}</button>)}</div></div></header>
 <div className="mx-auto grid max-w-7xl grid-cols-12 gap-5 p-5"><aside className="card col-span-12 p-3 md:col-span-3"><nav className="grid gap-2">{[['home','🏠 Dashboard'],['reading','📚 Reading Lab'],['writing','✍️ Writing Coach'],['progress','📈 Progress']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-4 py-3 text-left text-sm font-semibold ${tab===id?'bg-indigo-50 text-indigo-700':'hover:bg-slate-50'}`}>{label}</button>)}</nav><div className="mt-5 rounded-2xl bg-indigo-50 p-4 text-xs text-indigo-900"><b>Personal focus:</b><div className="mt-1">{focus==='balanced'?'Building a balanced foundation':focus}</div><div className="mt-2 text-indigo-700">New exercises automatically target the skill that needs the most practice.</div></div><div className="mt-3 rounded-2xl bg-slate-50 p-4 text-xs text-slate-600"><b>Coach rule:</b> feedback teaches Chaarvee how to improve; it does not write her answer for her.</div></aside>
 <section className="col-span-12 md:col-span-9">{tab==='home'&&<Dashboard stats={stats} focus={focus} setTab={setTab} />}
 {tab==='reading'&&<ReadingBuilder level={rLevel} setLevel={setRLevel} topic={rTopic} setTopic={setRTopic} type={rType} setType={setRType} length={rLength} setLength={setRLength} focus={focus} busy={busy} generate={generateReading} />}
 {tab==='reading-detail'&&<ReadingDetail reading={reading} answer={answer} setAnswer={setAnswer} ev={ev} busy={busy} evaluate={(rev=false)=>evaluate('reading',rev,ev)} back={()=>setTab('reading')} generated={generated}/>} 
 {tab==='writing'&&<WritingBuilder level={wLevel} setLevel={setWLevel} topic={wTopic} setTopic={setWTopic} type={wType} setType={setWType} focus={focus} busy={busy} generate={generateWriting}/>} 
 {tab==='writing-detail'&&<WritingDetail prompt={prompt} answer={answer} setAnswer={setAnswer} ev={ev} busy={busy} evaluate={(rev=false)=>evaluate('writing',rev,ev)} back={()=>setTab('writing')} generated={generated}/>} 
 {tab==='progress'&&<Progress history={history} focus={focus}/>}</section></div></main>
}
function Dashboard({stats,focus,setTab}:{stats:any;focus:string;setTab:any}){return <><div className="grid gap-4 md:grid-cols-3"><Stat title="Practice sessions" value={stats.count}/><Stat title="Average score" value={stats.avg?`${stats.avg}/40`:'—'}/><Stat title="Current skill focus" value={focus==='balanced'?'Balanced':focus}/></div><div className="card mt-5 p-7"><div className="text-xs font-bold uppercase tracking-widest text-indigo-600">Today’s adaptive path</div><h1 className="mt-2 text-3xl font-black">Read → Think → Write → Revise</h1><p className="mt-3 max-w-3xl text-slate-600">The coach generates a fresh, age-appropriate activity and targets the skill where Chaarvee has the most room to improve.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>setTab('reading')} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">Generate reading</button><button onClick={()=>setTab('writing')} className="rounded-xl border px-5 py-3 font-bold">Generate writing</button></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Feature title="Unlimited practice" text="Generate a fresh reading passage or writing prompt whenever she practices. Usage is limited only by your OpenAI/Vercel quotas and API budget."/><Feature title="Adaptive difficulty" text="The system uses recent rubric scores to guide the next exercise from Grade 8 through Grade 9 and AP/IB foundation."/></div></>}
function Stat({title,value}:{title:string;value:any}){return <div className="card p-5"><div className="text-sm text-slate-500">{title}</div><div className="mt-2 text-2xl font-black break-words">{value}</div></div>}
function Feature({title,text}:{title:string;text:string}){return <div className="card p-5"><div className="font-black">{title}</div><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>}
function SelectBox({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:any}){return <label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-3">{children}</select></label>}
function ReadingBuilder({level,setLevel,topic,setTopic,type,setType,length,setLength,focus,busy,generate}:{level:string;setLevel:any;topic:string;setTopic:any;type:string;setType:any;length:string;setLength:any;focus:string;busy:boolean;generate:()=>void}){return <div><h2 className="text-2xl font-black">Reading Lab</h2><p className="text-slate-500">Generate a fresh original passage at the level and topic you choose.</p><div className="card mt-5 p-6"><div className="grid gap-4 md:grid-cols-2"><SelectBox label="Level" value={level} onChange={setLevel}>{levels.map(x=><option key={x}>{x}</option>)}</SelectBox><SelectBox label="Topic" value={topic} onChange={setTopic}>{topics.map(x=><option key={x}>{x}</option>)}</SelectBox><SelectBox label="Reading type" value={type} onChange={setType}>{types.map(x=><option key={x}>{x}</option>)}</SelectBox><SelectBox label="Length" value={length} onChange={setLength}><option value="short">Short · 500–700 words</option><option value="medium">Medium · 800–1,000 words</option><option value="long">Long · 1,100–1,400 words</option></SelectBox></div><div className="mt-5 rounded-xl bg-indigo-50 p-4 text-sm"><b>Adaptive focus:</b> {focus==='balanced'?'balanced skill development':focus}. The questions and writing challenge will reinforce this area.</div><button onClick={generate} disabled={busy} className="mt-5 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?'Generating…':'Generate fresh reading'}</button></div></div>}
function WritingBuilder({level,setLevel,topic,setTopic,type,setType,focus,busy,generate}:{level:string;setLevel:any;topic:string;setTopic:any;type:string;setType:any;focus:string;busy:boolean;generate:()=>void}){return <div><h2 className="text-2xl font-black">Writing Coach</h2><p className="text-slate-500">Generate a new writing challenge targeted to Chaarvee’s current needs.</p><div className="card mt-5 p-6"><div className="grid gap-4 md:grid-cols-2"><SelectBox label="Level" value={level} onChange={setLevel}>{levels.map(x=><option key={x}>{x}</option>)}</SelectBox><SelectBox label="Writing type" value={type} onChange={setType}>{writingTypes.map(x=><option key={x}>{x}</option>)}</SelectBox><SelectBox label="Topic" value={topic} onChange={setTopic}>{topics.map(x=><option key={x}>{x}</option>)}</SelectBox></div><div className="mt-5 rounded-xl bg-indigo-50 p-4 text-sm"><b>Personalized skill:</b> {focus==='balanced'?'balanced skill development':focus}</div><button onClick={generate} disabled={busy} className="mt-5 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?'Generating…':'Generate fresh writing prompt'}</button></div></div>}
function ReadingDetail({reading,answer,setAnswer,ev,busy,evaluate,back,generated}:{reading:any;answer:string;setAnswer:any;ev:Eval|null;busy:boolean;evaluate:(rev?:boolean)=>void;back:()=>void;generated:boolean}){return <div><button onClick={back} className="mb-4 text-sm font-bold text-indigo-600">← New reading</button><article className="card p-7"><div className="text-xs font-bold uppercase tracking-widest text-indigo-600">{reading.level} · {reading.topic} · {reading.minutes||8} min</div><h2 className="mt-2 text-3xl font-black">{reading.title}</h2><div className="mt-6 whitespace-pre-line text-[17px] leading-8 text-slate-700">{reading.body}</div></article><div className="card mt-5 p-7"><h3 className="text-xl font-black">Think about it</h3><ol className="mt-4 list-decimal space-y-3 pl-6 text-slate-700">{(reading.questions||[]).map((q:string,i:number)=><li key={i}>{q}</li>)}</ol>{reading.writingChallenge&&<div className="mt-5 rounded-xl bg-indigo-50 p-4 text-sm"><b>Writing challenge:</b> {reading.writingChallenge}</div>}<textarea value={answer} onChange={e=>setAnswer(e.target.value)} className="mt-6 min-h-56 w-full rounded-xl border p-4 outline-none focus:ring-2 focus:ring-indigo-200" placeholder="Answer the questions and/or complete the writing challenge in your own words."/><div className="mt-4 flex gap-3"><button disabled={busy||answer.trim().split(/\s+/).length<60} onClick={()=>evaluate(false)} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-40">{busy?'Coaching…':'Get feedback'}</button>{ev&&<button disabled={busy} onClick={()=>evaluate(true)} className="rounded-xl border px-5 py-3 font-bold">Re-evaluate revision</button>}</div>{ev&&<Evaluation ev={ev}/>}</div></div>}
function WritingDetail({prompt,answer,setAnswer,ev,busy,evaluate,back,generated}:{prompt:any;answer:string;setAnswer:any;ev:Eval|null;busy:boolean;evaluate:(rev?:boolean)=>void;back:()=>void;generated:boolean}){return <div><button onClick={back} className="mb-4 text-sm font-bold text-indigo-600">← New prompt</button><div className="card p-7"><div className="text-xs font-bold text-indigo-600">{prompt.level} · {prompt.type} · {prompt.words||'350–450 words'}</div><h2 className="mt-2 text-3xl font-black">{prompt.title}</h2><p className="mt-4 rounded-xl bg-indigo-50 p-4 text-slate-700">{prompt.instruction}</p>{prompt.successCriteria&&<div className="mt-4"><div className="font-bold">Success criteria</div><ul className="mt-2 list-disc pl-5 text-sm text-slate-600">{prompt.successCriteria.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></div>}<textarea value={answer} onChange={e=>setAnswer(e.target.value)} className="mt-5 min-h-96 w-full rounded-xl border p-5 text-[16px] leading-7 outline-none focus:ring-2 focus:ring-indigo-200" placeholder="Write your response here. The coach evaluates your work and helps you revise it; it does not write the essay for you."/><div className="mt-3 flex items-center justify-between"><span className="text-sm text-slate-500">{answer.trim()?answer.trim().split(/\s+/).length:0} words</span><div className="flex gap-2"><button disabled={busy||answer.trim().split(/\s+/).length<100} onClick={()=>evaluate(false)} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-40">{busy?'Evaluating…':'Submit for coaching'}</button>{ev&&<button disabled={busy} onClick={()=>evaluate(true)} className="rounded-xl border px-4 py-3 font-bold">Re-evaluate revision</button>}</div></div>{ev&&<Evaluation ev={ev}/>}</div></div>}
function Evaluation({ev}:{ev:Eval}){return <div className="mt-7 border-t pt-7"><div className="flex items-end justify-between"><div><div className="text-sm font-bold text-slate-500">Coach evaluation</div><div className="text-4xl font-black">{ev.total}<span className="text-lg text-slate-400">/40</span></div></div><div className="rounded-full bg-indigo-50 px-4 py-2 text-sm font-bold text-indigo-700">{ev.next_level}</div></div><p className="mt-3 text-sm text-slate-600">{ev.coach_message}</p><div className="mt-5 grid gap-3 md:grid-cols-2">{rubric.map(k=><div key={k} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between text-sm"><span>{k}</span><b>{ev.scores?.[k]??0}/5</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-indigo-600" style={{width:`${((ev.scores?.[k]??0)/5)*100}%`}}/></div></div>)}</div><div className="mt-6 grid gap-5 md:grid-cols-2"><div><h4 className="font-black">What’s working</h4><ul className="mt-2 list-disc space-y-2 pl-5 text-sm text-slate-700">{ev.strengths?.map((x,i)=><li key={i}>{x}</li>)}</ul></div><div><h4 className="font-black">Your 3 priorities</h4><ol className="mt-2 list-decimal space-y-2 pl-5 text-sm text-slate-700">{ev.priorities?.map((x,i)=><li key={i}>{x}</li>)}</ol></div></div><div className="mt-5 rounded-2xl bg-amber-50 p-5"><div className="font-black">Revision goal</div><p className="mt-1 text-sm text-slate-700">{ev.revision_goal}</p></div></div>}
function Progress({history,focus}:{history:HistoryItem[];focus:string}){const avgs=history.length?rubric.map(k=>({k,v:Math.round(history.reduce((a,h)=>a+(h.scores?.[k]||0),0)/history.length*10)/10})).sort((a,b)=>a.v-b.v):[];return <div><h2 className="text-2xl font-black">Progress</h2><p className="text-slate-500">Your adaptive coach uses these scores to select the next skill focus.</p><div className="card mt-5 p-6"><div className="font-black">Current focus</div><div className="mt-2 text-xl text-indigo-700">{focus==='balanced'?'Balanced foundation':focus}</div>{avgs.length>0&&<div className="mt-5 grid gap-3 md:grid-cols-2">{avgs.map(x=><div key={x.k} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between text-sm"><span>{x.k}</span><b>{x.v}/5</b></div></div>)}</div>}</div><div className="card mt-5 overflow-hidden"><div className="grid grid-cols-4 border-b bg-slate-50 p-4 text-xs font-bold uppercase text-slate-500"><span>Activity</span><span>Score</span><span>Focus</span><span>Date</span></div>{history.length?history.map((h,i)=><div key={i} className="grid grid-cols-4 border-b p-4 text-sm"><span className="font-semibold">{h.activity}</span><span>{h.total}/40</span><span className="truncate">{h.focus||'—'}</span><span>{new Date(h.date).toLocaleDateString()}</span></div>):<div className="p-8 text-center text-slate-500">No sessions yet.</div>}</div></div>}
function weakestSkill(history:HistoryItem[]){if(history.length<2)return 'balanced';const avgs=rubric.map(k=>({k,v:history.reduce((a,h)=>a+(h.scores?.[k]??0),0)/history.length})).sort((a,b)=>a.v-b.v);return avgs[0]?.k||'balanced'}
